export const types = {
  FETCH_COMMENTS_START: 'FETCH_COMMENTS_START',
  FETCH_COMMENTS_FALIURE: 'FETCH_COMMENTS_FALIURE',
  FETCH_COMMENTS_SUCCESS: 'FETCH_COMMENTS_SUCCESS',
};

export default types;
