export const types = {
  FETCH_SERVICES_START: 'FETCH_SERVICES_START',
  FETCH_SERVICES_FALIURE: 'FETCH_SERVICES_FALIURE',
  FETCH_SERVICES_SUCCESS: 'FETCH_SERVICES_SUCCESS',
};

export default types;
