export const StylistTypes = {
  SET_CURRENT_STYLIST: 'SET_CURRENT_STYLIST',
  FETCH_STYLIST_LIST_START: 'FETCH_STYLIST_LIST_START',
  FETCH_STYLIST_LIST_SUCCESS: 'FETCH_STYLIST_LIST_SUCCESS',
  FETCH_STYLIST_LIST_FAILURE: 'FETCH_STYLIST_LIST_FAILURE',
};
