export const StylistTypes = {
  SET_CURRENT_STYLIST: 'SET_CURRENT_STYLIST',

  FETCH_STYLIST_LIST_START: 'FETCH_STYLIST_LIST_START',
  FETCH_STYLIST_LIST_SUCCESS: 'FETCH_STYLIST_LIST_SUCCESS',
  FETCH_STYLIST_LIST_FAILURE: 'FETCH_STYLIST_LIST_FAILURE',

  FETCH_STYLIST_START: 'FETCH_STYLIST_START',
  FETCH_STYLIST_SUCCESS: 'FETCH_STYLIST_SUCCESS',
  FETCH_STYLIST_FAILURE: 'FETCH_STYLIST_FAILURE',

  FETCH_STYLIST_CONTENT_START: 'FETCH_STYLIST_CONTENT_START',
  FETCH_STYLIST_CONTENT_SUCCESS: 'FETCH_STYLIST_CONTENT_SUCCESS',
  FETCH_STYLIST_CONTENT_FAILURE: 'FETCH_STYLIST_CONTENT_FAILURE',
};
