export const types = {
  FETCH_REQUSETS_START: 'FETCH_REQUSETS_START',
  FETCH_REQUSETS_FALIURE: 'FETCH_REQUSETS_FALIURE',
  FETCH_REQUSETS_SUCCESS: 'FETCH_REQUSETS_SUCCESS',

  FETCH_SESSIONS_START: 'FETCH_SESSIONS_START',
  FETCH_SESSIONS_FALIURE: 'FETCH_SESSIONS_FALIURE',
  FETCH_SESSIONS_SUCCESS: 'FETCH_SESSIONS_SUCCESS',

  CONFIRM_REQUEST: 'CONFIRM_REQUEST',
};

export default types;
