export const OrganizerTypes = {
  SET_STYLIST_DATA: 'SET_STYLIST_DATA',

  FETCH_OVERVIEW_COMMENTS_START: 'FETCH_OVERVIEW_COMMENTS_START',
  FETCH_OVERVIEW_COMMENTS_FALIURE: 'FETCH_OVERVIEW_COMMENTS_FALIURE',
  FETCH_OVERVIEW_COMMENTS_SUCCESS: 'FETCH_OVERVIEW_COMMENTS_SUCCESS',

  FETCH_OVERVIEW_REQUESTS_START: 'FETCH_OVERVIEW_REQUESTS_START',
  FETCH_OVERVIEW_REQUESTS_FALIURE: 'FETCH_OVERVIEW_REQUESTS_FALIURE',
  FETCH_OVERVIEW_REQUESTS_SUCCESS: 'FETCH_OVERVIEW_REQUESTS_SUCCESS',
};

export default OrganizerTypes;
